### ISSUE TITLE
datahub - sort by "last updated" in French is too wide

### ISSUE THREAD

**Issue by fvanderbiest** [geonetwork/geonetwork-ui#1050]
It breaks the UI:

![image](https://github.com/user-attachments/assets/4f1b05de-15b9-4f36-9bea-6bd6ea5452f7)

**Comment by jahow** [comment]
This is fixed on main:

![image](https://github.com/user-attachments/assets/9ff8fd1e-ded2-4d3b-a97c-b17e84b458fc)
