### ISSUE TITLE
[datahub] shouldnt fetch/display metadata templates

### ISSUE THREAD

**Issue by landryb** [geonetwork/geonetwork-ui#215]
on a testing instance with gn4, the catalog on `/geonetwork/` shows 77 metadata (as anonymous user), but a datahub instance deployed on the same georchestra (via georchestra/ansible#93) shows 105 entries. it seems to me that all the geonetwork **templates** are also displayed.. which is confusing.
![image](https://user-images.githubusercontent.com/3421760/150345680-24a5e74d-d2a8-4a24-8fc3-ea4eb18b4339.png)

@fvanderbiest @pmauduit ?

**Comment by landryb** [comment]
![image](https://user-images.githubusercontent.com/3421760/150354622-0d7a6190-21dc-4207-9d13-820758e56061.png)

vs

![image](https://user-images.githubusercontent.com/3421760/150354671-8a81108b-b86b-4631-94c4-463f4fe1156a.png)

**Comment by fgravin** [comment]
Salut @landryb,

Oui pour le moment il n'y a aucun filtre dans la recherche du datahub.
Dans GN on a par défaut un filtre sur les templates

```json
{
    "isTemplate": [
        "n"
    ]
}
```

**Comment by landryb** [comment]
dunno when it changed, but indeed there's `isTemplate:n`  in the default datahub request - so closing.
