### ISSUE TITLE
datafeeder - lang calculation fails in some browsers

### ISSUE THREAD

**Issue by pmauduit** [geonetwork/geonetwork-ui#228]
Tested on firefox, I had the following lookup failing:
https://github.com/geonetwork/geonetwork-ui/blob/master/libs/ui/inputs/src/lib/chips-input/chips-input.component.ts#L48

because `this.translate.currentLang` was set to "en-US".

Applying the following hack fixed my issue:
https://github.com/georchestra/geonetwork-ui/commit/9a93021667c11358dae9a7b861e4c4331536b995

**Comment by jahow** [comment]
Done in https://github.com/geonetwork/geonetwork-ui/pull/453
