### ISSUE TITLE
Build docker images for apps

### ISSUE THREAD

**Issue by fvanderbiest** [geonetwork/geonetwork-ui#243]
Would it make sense to have github actions build docker images for the apps from this repository ?

Example workflow:
https://github.com/georchestra/georchestra/blob/master/.github/workflows/datahub.yml

**Comment by jahow** [comment]
I think so yes; each app could have its own docker image hosted e.g. here: https://github.com/orgs/geonetwork/packages.

**Comment by jahow** [comment]
Done, see: https://github.com/geonetwork/geonetwork-ui/tree/main/apps/datahub#with-docker
