### ISSUE TITLE
datahub build failure since #276

### ISSUE THREAD

**Issue by landryb** [geonetwork/geonetwork-ui#307]
dunno if there are specific requirements, but with npm 8.1.2/nodejs v16.13.1 the build fails
```
> nx run demo:build:production datahub
'_' is not found in schema
> nx run map-viewer:build:production datahub
'_' is not found in schema
> nx run search:build:production datahub
'_' is not found in schema
> nx run webcomponents:build:production datahub
'_' is not found in schema
> nx run util-data-fetcher:build datahub
Compiling TypeScript files for project "util-data-fetcher"...
Done compiling TypeScript files for project "util-data-fetcher".
> nx run datahub:build:production datahub
'_' is not found in schema
 
 >  NX   Running target "build" failed
   Failed tasks:
   
   - datafeeder:build:production
   - demo:build:production
   - map-viewer:build:production
   - search:build:production
   - webcomponents:build:production
   - datahub:build:production
```
according to buildbot logs it started failing with #276.

the command run by the bot is `npm run build datahub -- --base-href="/datahub/"` after `npm i`.

after looking at the docs, i changed the command for `npm run build -- datahub --prod` but the failure is the same. And also same thing after ditching `node_modules`.

**Comment by fgravin** [comment]
The version is specified in https://github.com/geonetwork/geonetwork-ui/blob/master/package.json#L4
It works well with `16.14.12` and `8.5.0`, should work with your configuration.

In our case `npm run build` runs the `nx affected build` command and not the `ng build` command since https://github.com/geonetwork/geonetwork-ui/commit/8ee75df89247f1509d9e60c39938b569933c4324. Which was maybe not a good idea.

`nx affected build` compares the app from your working dir to `origin/main` and build only if the app has changed.
Seems something is missing for you so it can't compare and fails.

Try to use `npx nx build datahub` instead, it should work.

It's weird though cause the CI is able to run https://github.com/geonetwork/geonetwork-ui/blob/master/.github/workflows/main.yml#L50

We will push a fix to leave the `ng build` command available as a script.

**Comment by landryb** [comment]
thanks, that's definitely better... need readme updates ?
```
# npx nx build datahub
...
 >  NX   Successfully ran target build for project datahub and 1 task(s) it depends on (3m)
# ls -l dist/apps/datahub.zip 
-rw-r--r-- 1 buildbot buildbot 43816900 Sep 15 16:34 dist/apps/datahub.zip

```

**Comment by jahow** [comment]
This looks a lot like the dreaded node version 16.15.1 which brought stricter checks for peer dependencies... Could you please confirm your node version?

Thanks for reporting this btw

**Comment by jahow** [comment]
Actually I just reproduced these errors with node 16.17.0. The CI is using a slightly older version so it works there.

I'll try and address that ASAP, but from my experience since Angular is made of a big spaghetti bowl of dependencies solving these is sometimes not easy.

**Comment by jahow** [comment]
Please note that we specified in the package.json that the project shouldn't be used with node > 16.15.0 for this reason, see: https://github.com/geonetwork/geonetwork-ui/blob/7af02f7932530010726556dafb191caf7c809090/package.json#L5

**Comment by fgravin** [comment]
Yes, the 2 issues are not related.
The `peerDep` issues occurs because of a version of node > `16.15.0`

**Comment by landryb** [comment]
cant speak about the changes themselves, but i can confirm that building #311 with npm 8.15.0/node 16.17.0 gives me a successful build
```
 >  NX   Successfully ran target build for project datahub and 1 task(s) it depends on (2m)
```

thanks @jahow !

**Comment by landryb** [comment]
our georchestra buildbot building datahub is now green, thanks ;)

**Comment by Gaetanbrl** [comment]
Is it possible to detail npm / node version in the README ?

https://github.com/geonetwork/geonetwork-ui

**Comment by Gaetanbrl** [comment]
And other question,
Do you think it's possible to lock the node + npm version with package.json (and / or optionnal nvmrc file) ?

With a config like that (i dunno what is the best practice) : 

```
"engineStrict": true,
"engines": {
    "node": ">=8.9.0"
 },
```

**Comment by jahow** [comment]
Thanks for the suggestion @Gaetanbrl, I have clarified the minimum node requirement. The minimum version is already written in the package.json:
https://github.com/geonetwork/geonetwork-ui/blob/48fa80ba5434281e1dfd37d74db1ad8d16e22a57/package.json#L5

I don't think we can do much more (`engineStrict` is not part of the npm spec I think?).

**Comment by Gaetanbrl** [comment]
> engineStrict is not part of the npm spec I think?

Oh... seems true !

... and seems to avoid.
