### ISSUE TITLE
Add a new metadata Editor application

### ISSUE THREAD

**Issue by fgravin** [geonetwork/geonetwork-ui#339]
- [Technical proposal voted by the PSC](https://github.com/geonetwork/core-geonetwork/wiki/2022---Proposal:-a-new-metadata-editor)
- [The vision](https://www.camptocamp.com/en/news-events/news_new_metadata_editor_geonetwork)
- [The funding page](https://www.camptocamp.com/en/news-events/help-fund-the-new-geonetwork-editor)

![Image](https://user-images.githubusercontent.com/1491924/195568595-b6285dcd-d2de-4dd1-8a6e-4d9c36d40ccf.png)

**Comment by jahow** [comment]
The application has been created and work is ongoing
