### ISSUE TITLE
provide a geonetwork/geonetwork-ui-datahub:latest tag

### ISSUE THREAD

**Issue by fvanderbiest** [geonetwork/geonetwork-ui#415]
https://hub.docker.com/r/geonetwork/geonetwork-ui-datahub/tags?page=1&name=latest

So we can refer to it in the geOrchestra docker composition

**Comment by tkohr** [comment]
FYI, datahub images are now available with latest tag : https://hub.docker.com/r/geonetwork/geonetwork-ui-datahub/tags
