### ISSUE TITLE
support for html markup

### ISSUE THREAD

**Issue by h8that** [geonetwork/geonetwork-ui#45]
is it possible to add support for html markup in text fields example record here https://geonetwork-test.tern.org.au/geonetwork/srv/eng/catalog.search#/metadata/db766c37-f00d-4dc4-aa1a-325b284da1a0
thanks
Jenny

**Comment by jahow** [comment]
This has been discussed on [GeoNetwork's Gitter](https://gitter.im/geonetwork/core-geonetwork) recently and there was (I think) a consensus on allowing Markdown but not HTML in text fields. HTML used to be supported in GeoNetwork UI but it lacks interoperability and readability. @h8that if you're still interested please consider making a PR or funding someone to do it! Thanks a lot

**Comment by jahow** [comment]
Support for HTML in the metadata abstract has been implemented in the meantime, closing
