### ISSUE TITLE
[Datahub] Recognize CSV in harvested metadata from geoclip

### ISSUE THREAD

**Issue by cmoinier** [geonetwork/geonetwork-ui#520]
Geoclip provides an API that allows you to download data in CSV and XLSX formats, and we can easily retrieve it through web scraping, for example: https://www.geo2france.fr/datahub/dataset/act_cond_emp.pxx_sal15p_pre

You can download the file in CSV and XLSX formats. However, the file formats are not recognized, so it is not possible to filter by format type, and there is also no tabular preview available.

The XML code of the resource seems fine, as it matches well with other functioning records (for example: https://www.geo2france.fr/datahub/dataset/50f0712b-80e8-4b44-9e90-0cad4e5f64b0).

Two ideas :

- Either we can request to evolve the metadata protocol with DOWNLOAD:mime-type;
- or we can implement format detection from the URL.

**Comment by jahow** [comment]
Done in #578
