### ISSUE TITLE
[MEL] Error page after LDAP MEL login

### ISSUE THREAD

**Issue by cmoinier** [geonetwork/geonetwork-ui#525]
I connect to:

https://gateway.mel.integration.apps.gs-fr-prod.camptocamp.com/datahub/

I'm using the identity provider 'MEL.' After attempting to log in: https://gateway.mel.integration.apps.gs-fr-prod.camptocamp.com/datahub/?login=

This page returns the following error message:

### Whitelabel Error Page

This application has no configured error view, so you are seeing this as a fallback.
Mon Jun 19 08:02:12 UTC 2023
[80ef1128-16752] There was an unexpected error (type=Internal Server Error, status=500).

It seems that the server doesn't know which page to display upon returning from the LDAP login.

https://gateway.mel.integration.apps.gs-fr-prod.camptocamp.com/login?error
If I go back to the page, I see that I am successfully logged in. However, I can't navigate to the catalog, mapstore, or import. Instead, I get an error page similar to the one mentioned earlier.

If I log in with a local account, everything works fine.

**Comment by fgravin** [comment]
Not related to geonetwork-ui
