### ISSUE TITLE
[Datahub] Handle WFS links supporting only GML

### ISSUE THREAD

**Issue by cmoinier** [geonetwork/geonetwork-ui#526]
The GeoIDE V0 forms contain links to Mapserver which exposes a WFS which does not support the geojson format.

Ex https://www.geo2france.fr/geonetwork/srv/api/records/fr-120066022-jdd-f20f8125-877e-46dc-8cf8-2a8a372045eb/formatters/xml?approved=true

In the datahub, the tabular view is unavailable because it is based on the geojson.

1. support GML in the datahub
2. see with geoide so that they support geojson (present in carto2 but not in carto0)

**Comment by f-necas** [comment]
Fixed : #534
