### ISSUE TITLE
[Datahub] No resourceType in records harvested using the SimpleURL harvester

### ISSUE THREAD

**Issue by cmoinier** [geonetwork/geonetwork-ui#527]
The "resourceType"  field is not filled for records harvested by the SimpleUrl harvester.

Goal:

- [ ] The field should be set to "dataset" by default on all transformations
- [ ] This includes at least the OpenDataSoft transformation

**Comment by fgravin** [comment]
Not related to geonetwork-ui.
It relates core-geonetwork simple url harvester. @cmoinier you could report the issue in the core-geonetwork repository
