### ISSUE TITLE
[Datahub] Add a localisation filter input

### ISSUE THREAD

**Issue by cmoinier** [geonetwork/geonetwork-ui#529]
Sometimes, looking for something is not enough, we have to look for something somewhere.
Putting the location in the `any` search input is not accurate, cause it can miss larger scaled datasets.

eg. _velo chambery_ search won't find a _velo france_ dataset.

We will add the possibility to add a location input beside the full text search input like on the following screenshot.

![Screenshot from 2023-07-13 17-29-52](https://github.com/geonetwork/geonetwork-ui/assets/1491924/815fd661-c751-4fec-94d1-6cee9fc3ce90)

**Comment by fgravin** [comment]
Duplicates https://github.com/geonetwork/geonetwork-ui/issues/557
