### ISSUE TITLE
[Datahub] Datafeeder bug

### ISSUE THREAD

**Issue by cmoinier** [geonetwork/geonetwork-ui#530]
When I import data from the test datafeeder (for example, https://dev.geo2france.fr/geonetwork/srv/eng/catalog.search#/metadata/9985fe5e-6760-49ff-89d6-e6986719cce4), I can't find it using the search input on the datahub. It seems like it's not indexed (I can find it if I enter the complete URL in the browser: https://dev.geo2france.fr/datahub/dataset/9985fe5e-6760-49ff-89d6-e6986719cce4).

**Comment by fgravin** [comment]
Not related to geonetwork-ui
