### ISSUE TITLE
Pivot format as internal format

### ISSUE THREAD

**Issue by fgravin** [geonetwork/geonetwork-ui#551]
There is no real actual domain definition. Models design have been defined incrementally, mostly mapped on Elastisearch models.

We want to introduce a real domain definition, within the `common/domain` library, just defining types and interfaces with clean architecture in mind.
- Models (DTO)
- Repository (Interface)

The core component of this domain will be the **Metadata Record** type which will be based on the pivot format.
The pivot format will be the core model for any transformation (schemas, ogc api etc...).

**Comment by jahow** [comment]
Closed by #464
