### ISSUE TITLE
[Datahub]: Multilingual search

### ISSUE THREAD

**Issue by fgravin** [geonetwork/geonetwork-ui#556]
ATM the Datahub can be configured to be used for one lang only (or `*`). This will search only in specific languages fields from the index (eg. `default, eng, fre, ita`).

The search is then not optimized if the metadata are multilingual.
We will add this support.

**Sponsored by SwissTopo geocat.ch**

**Comment by jahow** [comment]
Let's keep this issue to track the work left on multilingual search :)
