### ISSUE TITLE
[Datahub]: incorrect URL display in browser 

### ISSUE THREAD

**Issue by mvadin** [geonetwork/geonetwork-ui#573]
I have installed the datahub for a member of DataGrandEst in a specific url.
I use a geonetwork subportal in order to power the datahub.

https://www.datagrandest.fr/public/region-grand-est/datahub/

Datahub displays metadata the correct way.

But the URL displayed in the browser https://www.datagrandest.fr/public/region-grand-est/datahub/home/news goes in a "not found page".

And datasets you have in the "see also" ("voir aussi" ) in the bottom of the page also go to not found page.
for example : https://www.datagrandest.fr/public/region-grand-est/datahub/dataset/FR-200052264-A0102-0001

Regards,

**Comment by jahow** [comment]
This is most likely an issue with the configuration of the HTTP server that serves the datahub.

See for example the NGIX conf used in the Dockerfile:
https://github.com/geonetwork/geonetwork-ui/blob/main/tools/docker/nginx.apps.conf

```
        location / {
          try_files $uri $uri/ /APP_NAME/index.html;

          add_header Cache-Control 'max-age=86400'; # 24h
        }
```

If the file is not found at the given URL then NGINX falls back to the `index.html` file at the root of the Datahub app. If you don't have this fallback logic then accessing any page beyond the datahub root will give a 404.

This has to be better documented though, thanks for reporting:

**Comment by jahow** [comment]
Another option would be to show the services as part of the authenticated backoffice of the datahub; then we would be able to show a slightly more technical view of the metadata content, e.g. available layers and protocols in the service.

Maybe this would make more sense in terms of the intended audience @fvanderbiest?

**Comment by f-necas** [comment]
Hello @mvadin, 

What revers-proxy are you using ? Could you share your actual configuration ? 

Thanks a lot

**Comment by fvanderbiest** [comment]
Florian, the datahub is here deployed manually by the customer in an apache "public" directory that we manage (cc @pmauduit )

**Comment by f-necas** [comment]
https://github.com/geonetwork/geonetwork-ui/pull/582
