### ISSUE TITLE
Datahub: organizations request failure not explicit

### ISSUE THREAD

**Issue by fgravin** [geonetwork/geonetwork-ui#697]
At the moment, the Datahub fetches the GN backend version to implement the correct organization request payload.
If the GeoNetwork does not support the Datahub, eg version 4.0.1, the Datahub crashes silently.
1. If the detected version is too low, then we should not fetch the organization, as there is no appropriate strategy
2. A warning should warns in the console that the version is too low.

**Comment by jahow** [comment]
I agree it would be nice to have a proper "platform" service that checks the version and raises a warning if the backend platform is not compatible

**Comment by fgravin** [comment]
It has been decided to
- check for the version compatibility
- if it's not compatible then
  - throw an error in the search
  - log the error in the console

It means that we don't support degraded mode, if the version is not ok, then the search is in error
