### ISSUE TITLE
[Datahub] Rework the dataset detail page

### ISSUE THREAD

**Issue by fgravin** [geonetwork/geonetwork-ui#722]
The metadata detailed page will be reworked, to add more informations while keeping great readability and experience.

Rework the page header
At the top of page, we'll put emphasis on

- [x] If it's a geospatial dataset or not
- [x] The date of the last modification of the dataset
- [x] The status of the metadata

On the right panel

- [x] Display the thumbnail of the metadata (optional)
- [x] Gives more information about the contact

In the content expandable section

- [x] Re-organize the information
- [x] Add contact informations
- [ ] Add temporal extent
- [x] Give more informations about the record

In the preview section

- [ ] add the spatial extent if any, and if no data are visualisable on the map

**Sponsored by SwissTopo geocat.ch**

**Mockup**

![Fluid Layout (1)](https://github.com/geonetwork/geonetwork-ui/assets/1491924/661dbd27-e465-4950-a4ae-6f234cf3075f)

**Comment by IGNF-Xavier** [comment]
Aperçu, API, Liens, Voir aussi won't be directly accesible thanks to a menu at the top of the dataset page.
In the actual version, this feature is interesting

**Comment by jahow** [comment]
> Aperçu, API, Liens, Voir aussi won't be directly accesible thanks to a menu at the top of the dataset page. In the actual version, this feature is interesting

Good point, looks like the floating top bar is gone in that design! @lucilecollignon was that intentional?

**Comment by fgravin** [comment]
All have been implemented but the Spatial Extent
