### ISSUE TITLE
[Datahub] Improve the advanced filter content for "format" dropdown

### ISSUE THREAD

**Issue by fgravin** [geonetwork/geonetwork-ui#724]
At the moment, the list of available formats are not readable enough.

**Todo**

Rework the content of this list by using Elastic Search pipeline to index human readable formats.

![image](https://github.com/geonetwork/geonetwork-ui/assets/1491924/d7816742-bfa9-484d-b54e-6c26174bc092)

**Sponsored by Géo2France**

**Comment by jahow** [comment]
Implementation done in #659 

Remaining: offer a public docker image that packages the pipeline and lets using it easily in a docker environment
