### ISSUE TITLE
[Datahub] Add a "contact us" panel

### ISSUE THREAD

**Issue by fgravin** [geonetwork/geonetwork-ui#725]
Display a "contact us" panel on the home page (news feed) of the datahub. This will only show up if an optional "contact_email" setting is present in the configuration file.

**Mockup**
![image](https://github.com/geonetwork/geonetwork-ui/assets/1491924/b8cb188f-ceef-438c-93e1-559da21a8b71)

**Sponsored by Métropole Européenne de Lille**

**Comment by IGNF-Xavier** [comment]
Will the contact-us panel be implemented on the dataset page in order to contact the owner of the dataset?

**Comment by jahow** [comment]
> Will the contact-us panel be implemented on the dataset page in order to contact the owner of the dataset?

No, this is a generic contact point for the catalog. On each dataset the email of the contact should be visible if it is present in the metadata.

**Comment by IGNF-Xavier** [comment]
Thansk, i was mislead by the peview in this issue : https://github.com/geonetwork/geonetwork-ui/issues/723

**Comment by jahow** [comment]
Done in #747
