### ISSUE TITLE
[Datahub] Add comments & discussion module on the record page

### ISSUE THREAD

**Issue by IGNF-Xavier** [geonetwork/geonetwork-ui#731]
On each datasets page, allow users to write a comment about the datasets.
Each comment is sent to the owner of the dataset.
The owner can reply to the comment ont the datasets page (transparency)
I suggest to allow comments only when connected.

Maybe in the back-office, foresee a listing of theses interactions between the user and the owner of the datasets in order to directly go to the datasets page where there is an exchange between them.
**[Wish]**

**Comment by IGNF-Xavier** [comment]
With https://www.ogc.org/standard/guf/?

**Comment by jahow** [comment]
Thanks, this has been a long standing wish for the Datahub application. GeoNetwork has an API for user feedbacks, so we have to evaluate whether this will work for our needs

**Comment by fgravin** [comment]
Original mockups

![image](https://github.com/geonetwork/geonetwork-ui/assets/1491924/7f8f79c6-5d87-4954-beca-ee9ce9d5183d)

**Comment by IGNF-Xavier** [comment]
Splendid

**Comment by fgravin** [comment]
Hello @IGNF-Xavier, may you please help us to clarify your intention about this story, and the other ones.

Are you expressing
- a whish
- a contribution
  - by providing the code
  - by providing some financial support

Could you please clarify the issues that your own with those informations ?
It would help us to have a better vision of the potential timeline of those modules, and integrate them in the roadmap.

Thank you very much :pray:

**Comment by IGNF-Xavier** [comment]
Ok i will explain the tickets.
https://github.com/geonetwork/geonetwork-ui/issues/733 : contribution
https://github.com/geonetwork/geonetwork-ui/issues/731 : wish
https://github.com/geonetwork/geonetwork-ui/issues/732 : wish
https://github.com/geonetwork/geonetwork-ui/issues/720 : contribution.

Very soon a contribution : prepackaged download module

**Comment by jahow** [comment]
You can see the doc on a local instance: http://localhost:8080/geonetwork/doc/api/index.html#/userfeedback
![image](https://github.com/geonetwork/geonetwork-ui/assets/10629150/61d07b06-b317-4fa4-a21b-3cc3e8b4bb45)

**Comment by jahow** [comment]
closed by #849
