### ISSUE TITLE
[IGN] [Datahub] Add markdown support on metadata-info component

### ISSUE THREAD

**Issue by cdebarros** [geonetwork/geonetwork-ui#733]
Hi, another feature i'd like to introduce.

We are going to use markdown as our metadata formatted text language (only the descriptive part). 
So we need somehow to implement a markdown parser like [marked](https://marked.js.org/) to render markdown content as html. 

Here is the kind of result i achieved to get.

Before: 
![Capture d’écran du 2023-12-18 17-48-09](https://github.com/geonetwork/geonetwork-ui/assets/45257663/2c9a1f70-e8e4-4853-b9b4-d983bb103cdd)

Before: 
![Capture d’écran du 2023-12-18 17-48-36](https://github.com/geonetwork/geonetwork-ui/assets/45257663/26618000-c343-4562-aa86-28b41e66483a)

It can be an optional setting in the toml file settings. And maybe extend it to others formatted text language ?

**Comment by jahow** [comment]
I completely agree on using Markdown as the format for rich text fields (abstract, lineage etc.).

Currently the Datahub has a very simplistic approach, it will render the content of the abstract as HTML, so if there are HTML tags in it they will show up correctly. One thing that I was considering was to convert all HTML tags to Markdown at some point in the process, and have the metadata page simply render Markdown and not worry about the rest.

Other formatting languages can include RST but this is too elaborate, and I think Markdown is the right compromise as a common language.

**Comment by cdebarros** [comment]
I did this feature, if i can contribute somehow.

I created a new ui-elements component to parse markdown content.
I used [marked](https://marked.js.org/) to parse the content and [github-markdown-css](https://github.com/sindresorhus/github-markdown-css) to style elements.

Do i need some specific rights to push a new branch ? (or maybe should i fork the project ?)

**Comment by jahow** [comment]
Please fork the project and open a Pull Request through Github, then a reviewer can examine your contribution and give you feedback. Thank you very much!

Also, please note that this change is not trivial since simply switching to MD instead of rendering HTML will break the appearance of many records that rely on HTML-based content (which the datahub currently handles).

**Comment by cdebarros** [comment]
Thanks for your feedback, i will fork the project and open a pull request soon (today or in january after holidays).

From what i've tested, [marked](https://marked.js.org/) can take markdown and html content as input: 
- html content will render as it is, with no changes
- markdown content is converted and rendered as html

The thing that can change, is the way we handle styling. 
Shall we apply the default [github markdown css](https://github.com/sindresorhus/github-markdown-css) to whatever input we get ?

**Comment by jahow** [comment]
Thanks for the clarification, it sounds like `marked` will make everything quite simple! For styling I wouldn't bring in another library, instead we can probably define some basic styles for the following elements:
* `h1` to `h6`
* `ul`, `ol` and `li`
* `p`
* `a`

That should be enough to have a basic layout showing up.

**Comment by cdebarros** [comment]
I see, it makes more sense this way.
I will make this change and open a pull request when it's done.
