### ISSUE TITLE
INSPIRE Validation: Wrong error message when API key quota is exceeded

### ISSUE THREAD

**Issue by fabiovinci** [geonetwork/geonetwork-ui#743]
During the INSPIRE Validation if the API key quota is exceeded the following error message is shown:

![image](https://github.com/geonetwork/geonetwork-ui/assets/22212406/b88052cb-48f6-455e-80c6-b81f3c728d4d)

The error message should be improved since:

1.  The quota available is on a weekly basis (200 requests/week) and it is reset every Sunday night.
2.  There is no possibility to extend the quota and/or remove the limitation

So, the error message could be:
"_You have exceeded the weekly quota (200 requests) assigned to your API key. It will be reset Sunday night._"

**Comment by jahow** [comment]
Hi,

It looks like this issue would be better suited here: https://github.com/geonetwork/core-geonetwork/issues, since this issue is not related to the GeoNetwork-UI project.

**Comment by fabiovinci** [comment]
Dear @jahow,

thank you for your suggestion, I opened it in the main repository.
