### ISSUE TITLE
Question : Which attribute of metadata for the search query

### ISSUE THREAD

**Issue by IGNF-Xavier** [geonetwork/geonetwork-ui#888]
Hello,
Does the search on "thème" correspond to TopicCategory in the metadata?
![image](https://github.com/geonetwork/geonetwork-ui/assets/98382923/7f8a0574-139d-4754-a3b0-5d779e2f9a19)

Thanks

**Comment by jahow** [comment]
Exactly! see https://geonetwork.github.io/geonetwork-ui/main/docs/reference/search-fields.html#topic

**Comment by IGNF-Xavier** [comment]
Thanks i have seen the docs but i was not sure because the documentation mentioned Topic and not Topic Category.

Many thanks for the confirmation
