### ISSUE TITLE
Question which version of WFS is supported for the mapviewer

### ISSUE THREAD

**Issue by IGNF-Xavier** [geonetwork/geonetwork-ui#911]
We have an information which said that "Class of objects is not find" on the default mapviewer
Maybe this is due to the version of WFS supported by the mapviewer.

Version of GPF WFS https://data.geopf.fr/wfs/ows?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities is 2.0.0

Does the mapviewer support it?

**Comment by jahow** [comment]
Yes it does support all versions of WFS. Do you have an example of a record that showcases the error?

**Comment by IGNF-Xavier** [comment]
I have noticed it on my qualif environment of Geoplateforme.
THis WFS is also availaboe on https://data.geopf.fr/wfs/ows?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetCapabilities but i have no datahub connected to it.
It was resources of RPG.

**Comment by jahow** [comment]
GeoNetwork-UI relies on ogc-client, you can test the WFS with it here: https://camptocamp.github.io/ogc-client/#/demo

**Comment by IGNF-Xavier** [comment]
Merci je vais clore le ticket, je pense que le problème est chez nous
