### ISSUE TITLE
Auto load when scrolling

### ISSUE THREAD

**Issue by f-necas** [geonetwork/geonetwork-ui#943]
### Description

On home page and search page,  automatically load "More Results" when reaching the bottom of the page.

### Motivation

So long to scroll > click > scroll > click

### Inspiration and context

Every feed content

**Comment by jahow** [comment]
We intentionally moved away from auto-loading (aka infinite scrolling) because it is often considered a "dark pattern" and having a button was considered better design. Note that the results-list component can still work with infinite scrolling, it's just not offered in the Datahub.

**Comment by f-necas** [comment]
Make sense ! Using a more accurate search is better. 

Could it be a configuration variable ? Don't know if end users, platform admins would like it.
