### ISSUE TITLE
No "lire la suite"

### ISSUE THREAD

**Issue by IGNF-Xavier** [geonetwork/geonetwork-ui#978]
### Describe the bug

When having a metadata with description in markdown, there is no "lire la suite" when the text is very long on the le page of the data.

**Comment by IGNF-Xavier** [comment]
Sorry but the metadata  on this website https://cartes.gouv.fr/catalogue/search don't have markdown for now
I attached a XML used in your development environment with this problem.
[metadataLIDARHD 1.zip](https://github.com/user-attachments/files/16840802/metadataLIDARHD.1.zip)
![image](https://github.com/user-attachments/assets/4470bcef-2358-495f-8755-99801d26f6fa)

I seems that GN-Ui recognizes line break in plain text but not in markdown text

**Comment by jahow** [comment]
Tried this record on the main branch and the "read more" button works as expected:

![image](https://github.com/user-attachments/assets/7fc5ad20-aa59-429c-9cea-51541c9761ca)

**Comment by IGNF-Xavier** [comment]
With the last version of datahub, it is ok
